import file from '@system.file';
import router from '@system.router';
import app from '@system.app';
import brightness from '@system.brightness';

export default {
  data: {
    wordsStr: " APRILARTPLEPLYRONTERTLY ASIANHENIDEKEWPENSET DUTCHDEDDESLLYMMYMPYNCENNOSKYSTYVET GREEKACEADEAFTAINANDANTAPEAPHASPASSATEAVEAVYAZEEATEEDEENEETIEFILLIMEIMYINDIPEOANOINOOMOPEOSSOUPOVEOWLUELUFFUNT ISLAMSUE LATINBELBORDLEGERMERNCENKYPELRGESERTCHTERTEXUGHXERYER NEGROEDYIGHRVEVERWERWLYWSY SATANBERDESDLYFERGERINTLADLLYLONLTYLVENDYNERSSYTINUCEUCYUNAUTEVERVORVVY ABACKATEBEYETSHORIDELERORTOUTOVEUSEYSS ACORNRIDTORUTE ADAGEAPTEPTMITOBEOPTOREORNULT AFFIXOOTTER AGAINENTILELOWONYREE AHEAD AISLE ALARMBUMERTGAEIBIIENIGNIKEIVELAYLEYLOTLOWLOYOFTONEONGOOFOUDPHATARTER AMASSAZEBERBLEENDISSONGPLEPLYUSE ANGELGERGLEGRYGSTKLENEXNOYNULVIL AORTA ARBORDORENAGUEISEMOROMARAYROWSON ATLASONETIC AUDIODITRAL AVAILERTOID AWAITAKEARDARE AXIOM AZURE BABELCONDGEDLYGELGGYKERLMYNALNDYNJORERRGERONSERSICSILSINSTETCHTONWDYYOU BEACHADYARDASTECHEFYFITGINIGELCHLIELLYLOWNCHRETRRYRTHSET BOORSARDASTGUSNUSOBYOSTOTHOTYOZESOMSSYTCHUGHWELXER BIBLENGOPEDRCHRTH BLACKADEAMEANDANKAREASEASTAZEEAKEATEEDENDESSIMPINDINKISSITZOCKOGSONDOODOOMUERUFFUNTURBURTUSH BRACEAIDAINAKEANDASHASSAVEAVOAWLAWNEADEAKEEDIBEICKIDEIEFINEINGINKINYISKOADOILOODOOKOOMOTHOWNUNTUSHUTE BUDDYDGEGGYGLEILDLGELKYLLYMPYNCHNNYOYSRLYRRORSTSHYXOMYER CABINBLECAOCHECTIDETGEYLKSLVEMELMEONALNDYNNYNOENONPERRATRGOROLRRYRVETCHTERULKUSEWED CEASEDARLLO CHAFEAFFAINAIRALKAMPANTAOSARMARTASEASMEAPEATECKEEKEEPEERESSESTEWYICKIDEIEFILDILIILLIMEIMPINAINKIRPOIROKEORDOREUCKUNKURNUTE CIDERGARNCHRCAVICVIL CLACKAIMAMPANGANKASHASPASSEANEAREATEFSERKICKIFFIMBIMEINGINKOAKOCKONEOSEOTHOUDOUTOVEOWNUCKUMP COACHCKYCOALICLONLORMICRALRNYRPSUCHUNTURTVERWERYER CRACKAFTAMPANEANKASHASSATEAVEAWLAZEAZYEAKEAMEEDEEKEEPEPEESTIMEISPOAKOCKONYOOKOONOSSOWDOWNUDEUELUMBUSHUSTYPT CUBICRIORLYRRYRSERVETER CYCLENIC DADDYILYIRYISYLLYNCENDYTUMUNT DEATHCAYEDSIFYIGNLTALVENIMPTHTERVIL DOOPSDGEGMAILYLLYNORPEYTESUBTUGHUSEWDYWRYZEN DIARYMERMLYNERNGYRERRGERTYSCOTTOTTYVERZZY DRAFTAINAMAINKAPEAWLEADEAMESSIERIFTILLIVEOLLONEOOLOOPOSSOWNYERYLY DWARFELL EAGERGLERLYRTHSELTER EBBEDONY EDGERICT EERIE EGGED EIGHT EJECT ELBOWDERECTEGYITEOPEUDEVES EMBERPTY ENDOWEMAEMYTERVOY EPOCH EQUALUIP ERECTODERORUPT ESSAY ETHERHICHOS EVADEENTERYICTOKE EXALTCELERTILEPELTOLTRAUDEULT FABLECETGOTINTIRYITHLSENCYRCETALTTYULTUNAVOR FEASTCESIGNINTLONNCERRYTCHTIDTUSVERWER FIBERCHEELDENDERYFTHFTYGHTLCHLETLLYLMYLTHNALNCHNERRSTSHYVERZZY FLAILAIRAKEAKYAMEANKAREASHASKECKEETESHICKIERINGINTIRTOATOCKOODOORORAOSSOUROUTUFFUIDUKEUNKUSHUTE FOAMYCALCUSGGYISTLLYRAYRCERGERGORTHRTYRUMUNDUNTYER FRAILAMEANCANKAUDEAKEERESHIARILLISKOCKONDONTOSTOTHOWNUIT FUDGELLYNNYRLSRORRRYSSYZZY GABLEILYMERMMAMUTUDYUGEUNTUZEVELWKYYER GOOSEDLYNERNGSNNAODYOEYOFYRGEUGEURD GENIENIINRENTSNUS GHOSTOUL GIANTDDYLLSMMERTH GLADEANDAREASSAZEEAMEANIDEINTOATOBEOOMORYOSSOVE GNARLASHATSOME GUARDESSESTIDEILDILEILTISELCHLLYMMYPPYSTY HABITIRYLERLONLVENDYPPYRDYREMRRYRSHRTSSTYTCHUNTVENVOCZEL HEADYARTATHAVEAVYDGEFTYLLONCERON HIKERLLYTCH HOARDBBYISTLLYMEYNEYNORRDERNYTELTLYUNDUSEVELVER HUFFYGERMANMIDMORNCHRRYSKYTCH HYENA ICIER IDEALLER IGLOO IMAGEPELPLY INANECURDEXEPTERTFERFIXLAYLETNERPUTTER IRATEONY ITCHY IVIESORY JAMBSUNT JELLYRKYTTYWEL JIFFYLTS JOINTKERLLY JUDGEICEICYMBOMPYNTAROR KAYAK KHAKI KILOSNDANKYOSKTTY KNACKEADEELOOSIFEOCKOLL KOALA LEACHAFYAKYARNASEASHASTAVEDGEECHEKSERYGALMMEMONPERTUPVEEVELVER LIBELGHTKENKERLACMBOMITNENNERNGOSPSTERTHEVENVERVID LLAMA LOATHBBYCALDGEFTYGICONYOSERRYSERTUSUSEUSYVERWERWLYYAL LUCIDCKYMPYNARNCHRCHRIDSTY LYMPHNCHRESRIC MACEDCESCHODAMDLYGICIMSIZEJORKERNGENGONGYNIANICNLYNORPLERCHRIARRYRSHSONTCHUVEYBEYOR MEALYDALLONOWSRCYRGERITRRYSSYTALTEDTERTESTRO MILKYMICNCENERNORNUSRTHSTYXER MODALDELISTLARLDYNEINTHODYPEDPESRALRNSRONSSYTELTIFTORTTOUNDUNTURNUSEUSYUTHVERVIEWER MUCUSDDYGGYLCHLTIMMYMPSNCHRALRKYSHYSICSTYTER NAIVEKEDPESPPYSALSTYTTYVALVEL NICERCHEECEFTYGHTNNINTHPPY NOBLEBLYISEISYMADOSERTHTCHVEL NUDERDGERSETTY NYLONMPH OAREDSIS OBESEOES OCCUREANTAL ODDERDLY OFTEN OGLESRES OKAYS OLDENDERIVE OMEGA ONIONSET OPERAIUMTIC ORBITDERGAN OTHERTER OUGHTNCE OVARY OWNER OXIDE OZONE PADDYGANGERINTLERNELNICNSYPALPERRCHRKARTYSTASTYTCHTIOTTYUSEYER PEACEACHARLCANEVENALNCENDSNISNNYONSONYRCHRKYSKYTALTERTTY PHASEONEONYOTO PIANOCKYECEETYLOTNCHOUSQUETCHTHYVOTXIEZZA PLACEAIDAINANEANKANTATEAZAEADEATUCKUMBUMEUMPUSH POACHINTISEKERKEYLARLIOLKAOPSPPYRCHUCHUNDWER PRANKAWNESSICEICKIDEIMEIMPINTIORISMIVYIZEONGOUDOVEOWLOXYUDEUNE PSALM PUCKSDGYFFYLSENCHPILPPYRERRGERSESHYSSYTTY QUACKAILAKEALMARKARTASHEENEERELLERYESTEUEICKIETILLILTIRKOTAOTE RABBIBIDCERDARDIOINYISELLYNCHPIDRERTIOTTYVELVENWERYONZOR REACHADYALMIGNLICMITPELVEL ROODSACHASTBINBOTCKYDEOGUEMANOMYOSTSISTORUGEUGHUNDUSEWDYYAL RHINOYME RIDERDGEFERFLEGHTGIDGORNSEPENPERSERSKYVALVERVET RUDDYDERGBYLERMMYMORNNYRALSTY SCALDALEALPALYANTAREARFARYENEENTOFFOLDOOPOOTOPEOREORNOUROUTOWLRAMRAPREWRUBUFF SEDANEDYIZEMENNSERUMRVEVENVERWER SHACKADEADYAFTAKEAKYALLAMEAPEAREARKARPAVEAWLEAFEAREENEEPEEREETELFELLIFTINEINYIREIRKIRTOALOCKOOTORTOUTOWYREDREWRUBRUGUCKUNTYER SIDLEEGEEVEGHTGMALLYLTSNCENUSRENSSYXTHXTYZER SKEATEINILLIMPIRTULKULLUNK SLACKAKEANGANTASHATEAVEEDSEEKEEPEETICEICKIDEIERIMEIMYINGINKOPEOSHOTHUMPUSHUTSYLY SMACKALLARTASHEARELLILEIRKITEOCKOKEOKYUTS SNACKAILAKEAREARLEAKEERIDEIFFIPEOOPOREORTOTSOUTOWYUFF SOAPYBERGGYLARLIDLVENICOTYRERRRYRTAUNDUTH SPACEADEANKAREARKASMATEAWNEAKEARECKEEDELLENDERMICEICYIKEILLINEIREITELATLITOILOOFOOKOOLOONOREORTOUTRAYREERIGURNURT SQUADUATUID STACKAFFAGEAIDAINAIRAKEALEALKALLAMPANDINKAREARKARTATEAVEEAKEALEAMEELEEPEERERNICKIFFILLINGINTOCKOKEOMPONEONYOOLOOPOREORKORMORYOUTOVEOWSRAPRAWRAYREWRIPRUMRUTUDYUFFUMPUNTYLE SUAVEGARLKYNNYNUPPERRGERLY SWAMPARMEAREATEEPEETELLIFTILLINEINGIPEIRLISHOONOOPORD SYRUP TABBYBLEBOOCITCKYINTKERLLYLONMERNGOPERRDYRRYSTESTYTTYUNTWNY TEACHAKSMPOMPTNETNORNTHPEEPID TOONSOTHASTDAYKENNALNICNNYPAZPICRCHRSOTALTEMUCHUGHWELWERXICXIN THANKEFTEIREMEEREESEETAICKIEFIGHINGINKIRDONGORNOSEREEROWROBUMBUMPYME TIARADALGERGHTLDEMERMIDNGENNYPSYTLE TRACEACKACTADEAILAINAITAMPASHAWLEADEATENDICKILLIPEITEOLLOOPOUTUCEUCKUERULYUMPUNKUSTUTH TULIPMMYMORNERNICTOR TWANGEAKEEDEETICEINEIRLIST UDDER ULCERTRA UNCLETIL UPENDPERSET URBANINE USAGEHERUALURP UTERITER VAGUELETLIDLORLUELVEPORSISULT VENOMNUERGERSERVE VICARDEOGILGORLERLLANYLOLAPERRALRUSSITSORSTATALVID VOCALDKAGUEICEMITTERUCHWEL WAFERGERGONISTIVEKENLTZNNASTETCHTERVER WEARYAVEDGEEDYIGHIRD WHACKALEARFEATEELEREICHIFFILEINEIRLISKITEOLEOOPOREOSE WIDENDERDOWDTHELDNCENCHNDYPERSERSPYTCHTTY WOMANODYRDYRLDRRYRSERSTRTH WRATHEAKECKENSESTINGISTITEONGYER YACHT YEARNASTSES YIELD YODELKELUNGUTH ZEBRA",
    dictStr: '{"AP":7,"AS":6,"DU":11,"GR":36,"IS":2,"LA":17,"NE":8,"SA":23,"AB":12,"AC":4,"AD":9,"AF":3,"AG":6,"AH":1,"AI":1,"AL":22,"AM":10,"AN":10,"AO":1,"AR":10,"AT":3,"AU":3,"AV":3,"AW":4,"AX":1,"AZ":1,"BA":23,"BE":18,"BO":16,"BI":5,"BL":30,"BR":33,"BU":18,"CA":27,"CE":3,"CH":40,"CI":6,"CL":30,"CO":16,"CR":35,"CU":7,"CY":2,"DA":9,"DE":11,"DO":14,"DI":13,"DR":21,"DW":2,"EA":6,"EB":2,"ED":2,"EE":1,"EG":1,"EI":1,"EJ":1,"EL":8,"EM":2,"EN":5,"EP":1,"EQ":2,"ER":4,"ES":1,"ET":3,"EV":5,"EX":9,"FA":14,"FE":12,"FI":20,"FL":31,"FO":16,"FR":18,"FU":8,"GA":12,"GO":11,"GE":5,"GH":2,"GI":5,"GL":15,"GN":4,"GU":13,"HA":18,"HE":10,"HI":3,"HO":15,"HU":9,"HY":1,"IC":1,"ID":2,"IG":1,"IM":3,"IN":12,"IR":2,"IT":1,"IV":2,"JA":2,"JE":4,"JI":2,"JO":3,"JU":7,"KA":1,"KH":1,"KI":5,"KN":7,"KO":1,"LE":20,"LI":16,"LL":1,"LO":17,"LU":8,"LY":4,"MA":27,"ME":14,"MI":9,"MO":27,"MU":14,"NA":9,"NI":8,"NO":9,"NU":4,"NY":2,"OA":2,"OB":2,"OC":3,"OD":2,"OF":1,"OG":2,"OK":1,"OL":3,"OM":1,"ON":2,"OP":3,"OR":3,"OT":2,"OU":2,"OV":1,"OW":1,"OX":1,"OZ":1,"PA":20,"PE":18,"PH":4,"PI":13,"PL":15,"PO":14,"PR":20,"PS":1,"PU":13,"QU":20,"RA":18,"RE":8,"RO":19,"RH":2,"RI":15,"RU":9,"SC":25,"SE":10,"SH":41,"SI":14,"SK":8,"SL":26,"SM":13,"SN":17,"SO":13,"SP":37,"SQ":3,"ST":56,"SU":8,"SW":17,"SY":1,"TA":19,"TE":9,"TO":20,"TH":22,"TI":11,"TR":28,"TU":6,"TW":8,"UD":1,"UL":2,"UN":2,"UP":3,"UR":2,"US":4,"UT":2,"VA":9,"VE":5,"VI":16,"VO":8,"WA":12,"WE":6,"WH":17,"WI":13,"WO":8,"WR":10,"YA":1,"YE":3,"YI":1,"YO":4,"ZE":1}',
    progress: 0,
    errStr: null,
    strLen: 0,
    interval: null,
  },
  onInit() {
    brightness.setKeepScreenOn({keepScreenOn: true});
    this.strLen = this.wordsStr.length;
    file.rmdir({
      uri: "internal://app/words",
      recursive: true,
      complete: () => {
        file.mkdir({
          uri: "internal://app/words",
          success: () => {
            this.progress = 0;
            this.interval = setInterval(this.continueWrite, 50);
          }
        });
      }
    });
  },
  continueWrite() {
    while (this.progress < this.strLen && this.wordsStr[this.progress] === ' ') this.progress++;
    if (this.progress >= this.strLen) {
      clearInterval(this.interval);
      file.writeText({
        uri: `internal://app/words/dict`,
        text: this.dictStr,
        fail: data => {
          clearInterval(this.interval);
          this.errStr = data;
        },
        success: () => {
          file.writeText({
            uri: `internal://app/words/version`,
            text: app.getInfo().versionName,
            fail: data => {
              clearInterval(this.interval);
              this.errStr = data;
            },
            success: () => {
              return router.replace({uri: "/pages/index/index"});
            }
          });
        }
      });
      return;
    }

    const key = this.wordsStr[this.progress] + this.wordsStr[this.progress + 1];
    this.progress += 2;

    let vals = "";
    while (this.progress + 2 < this.strLen && this.wordsStr[this.progress] !== ' ') {
      const val = this.wordsStr[this.progress] + this.wordsStr[this.progress + 1] + this.wordsStr[this.progress + 2];
      this.progress += 3;
      vals += val;
    }

    file.writeText({
      uri: `internal://app/words/${key}`,
      text: vals,
      fail: data => {
        clearInterval(this.interval);
        this.errStr = data;
      }
    });
  },
}