import file from '@system.file';
import router from '@system.router';

export default {
  data: {
    wordsStr: " APRILARTPLEPLYRONTERTLY ASIANHENIDEKEWPENSET DUTCHDEDDESLLYMMYMPYNCENNOSKYSTYVET GREEKACEADEAFTAINANDANTAPEAPHASPASSATEAVEAVYAZEEATEEDEENEETIEFILLIMEIMYINDIPEOANOINOOMOPEOSSOUPOVEOWLUELUFFUNT ISLAMSUE LATINBELBORDLEGERMERNCENKYPELRGESERTCHTERTEXUGHXERYER NEGROEDYIGHRVEVERWERWLYWSY SATANBERDESDLYFERGERINTLADLLYLONLTYLVENDYNERSSYTINUCEUCYUNAUTEVERVORVVY ABACKATEBEYETSHORIDELERORTOUTOVEUSEYSS ACORNRIDTORUTE ADAGEAPTEPTMITOBEOPTOREORNULT AFFIXOOTTER AGAINENTILELOWONYREE AHEAD AISLE ALARMBUMERTGAEIBIIENIGNIKEIVELAYLEYLOTLOWLOYOFTONEONGOOFOUDPHATARTER AMASSAZEBERBLEENDISSONGPLEPLYUSE ANGELGERGLEGRYGSTKLENEXNOYNULVIL AORTA ARBORDORENAGUEISEMOROMARAYROWSON ATLASONETIC AUDIODITRAL AVAILERTOID AWAITAKEARDARE AXIOM AZURE BABELCONDGEDLYGELGGYKERLMYNALNDYNJORERRGERONSERSICSILSINSTETCHTONWDYYOU BEACHADYARDASTECHEFYFITGINIGELCHLIELLYLOWNCHRETRRYRTHSET BOORSARDASTGUSNUSOBYOSTOTHOTYOZESOMSSYTCHUGHWELXER BIBLENGOPEDRCHRTH BLACKADEAMEANDANKAREASEASTAZEEAKEATEEDENDESSIMPINDINKISSITZOCKOGSONDOODOOMUERUFFUNTURBURTUSH BRACEAIDAINAKEANDASHASSAVEAVOAWLAWNEADEAKEEDIBEICKIDEIEFINEINGINKINYISKOADOILOODOOKOOMOTHOWNUNTUSHUTE BUDDYDGEGGYGLEILDLGELKYLLYMPYNCHNNYOYSRLYRRORSTSHYXOMYER CABINBLECAOCHECTIDETGEYLKSLVEMELMEONALNDYNNYNOENONPERRATRGOROLRRYRVETCHTERULKUSEWED CEASEDARLLO CHAFEAFFAINAIRALKAMPANTAOSARMARTASEASMEAPEATECKEEKEEPEERESSESTEWYICKIDEIEFILDILIILLIMEIMPINAINKIRPOIROKEORDOREUCKUNKURNUTE CIDERGARNCHRCAVICVIL CLACKAIMAMPANGANKASHASPASSEANEAREATEFSERKICKIFFIMBIMEINGINKOAKOCKONEOSEOTHOUDOUTOVEOWNUCKUMP COACHCKYCOALICLONLORMICRALRNYRPSUCHUNTURTVERWERYER CRACKAFTAMPANEANKASHASSATEAVEAWLAZEAZYEAKEAMEEDEEKEEPEPEESTIMEISPOAKOCKONYOOKOONOSSOWDOWNUDEUELUMBUSHUSTYPT CUBICRIORLYRRYRSERVETER CYCLENIC DADDYILYIRYISYLLYNCENDYTUMUNT DEATHCAYEDSIFYIGNLTALVENIMPTHTERVIL DOOPSDGEGMAILYLLYNORPEYTESUBTUGHUSEWDYWRYZEN DIARYMERMLYNERNGYRERRGERTYSCOTTOTTYVERZZY DRAFTAINAMAINKAPEAWLEADEAMESSIERIFTILLIVEOLLONEOOLOOPOSSOWNYERYLY DWARFELL EAGERGLERLYRTHSELTER EBBEDONY EDGERICT EERIE EGGED EIGHT EJECT ELBOWDERECTEGYITEOPEUDEVES EMBERPTY ENDOWEMAEMYTERVOY EPOCH EQUALUIP ERECTODERORUPT ESSAY ETHERHICHOS EVADEENTERYICTOKE EXALTCELERTILEPELTOLTRAUDEULT FABLECETGOTINTIRYITHLSENCYRCETALTTYULTUNAVOR FEASTCESIGNINTLONNCERRYTCHTIDTUSVERWER FIBERCHEELDENDERYFTHFTYGHTLCHLETLLYLMYLTHNALNCHNERRSTSHYVERZZY FLAILAIRAKEAKYAMEANKAREASHASKECKEETESHICKIERINGINTIRTOATOCKOODOORORAOSSOUROUTUFFUIDUKEUNKUSHUTE FOAMYCALCUSGGYISTLLYRAYRCERGERGORTHRTYRUMUNDUNTYER FRAILAMEANCANKAUDEAKEERESHIARILLISKOCKONDONTOSTOTHOWNUIT FUDGELLYNNYRLSRORRRYSSYZZY GABLEILYMERMMAMUTUDYUGEUNTUZEVELWKYYER GOOSEDLYNERNGSNNAODYOEYOFYRGEUGEURD GENIENIINRENTSNUS GHOSTOUL GIANTDDYLLSMMERTH GLADEANDAREASSAZEEAMEANIDEINTOATOBEOOMORYOSSOVE GNARLASHATSOME GUARDESSESTIDEILDILEILTISELCHLLYMMYPPYSTY HABITIRYLERLONLVENDYPPYRDYREMRRYRSHRTSSTYTCHUNTVENVOCZEL HEADYARTATHAVEAVYDGEFTYLLONCERON HIKERLLYTCH HOARDBBYISTLLYMEYNEYNORRDERNYTELTLYUNDUSEVELVER HUFFYGERMANMIDMORNCHRRYSKYTCH HYENA ICIER IDEALLER IGLOO IMAGEPELPLY INANECURDEXEPTERTFERFIXLAYLETNERPUTTER IRATEONY ITCHY IVIESORY JAMBSUNT JELLYRKYTTYWEL JIFFYLTS JOINTKERLLY JUDGEICEICYMBOMPYNTAROR KAYAK KHAKI KILOSNDANKYOSKTTY KNACKEADEELOOSIFEOCKOLL KOALA LEACHAFYAKYARNASEASHASTAVEDGEECHEKSERYGALMMEMONPERTUPVEEVELVER LIBELGHTKENKERLACMBOMITNENNERNGOSPSTERTHEVENVERVID LLAMA LOATHBBYCALDGEFTYGICONYOSERRYSERTUSUSEUSYVERWERWLYYAL LUCIDCKYMPYNARNCHRCHRIDSTY LYMPHNCHRESRIC MACEDCESCHODAMDLYGICIMSIZEJORKERNGENGONGYNIANICNLYNORPLERCHRIARRYRSHSONTCHUVEYBEYOR MEALYDALLONOWSRCYRGERITRRYSSYTALTEDTERTESTRO MILKYMICNCENERNORNUSRTHSTYXER MODALDELISTLARLDYNEINTHODYPEDPESRALRNSRONSSYTELTIFTORTTOUNDUNTURNUSEUSYUTHVERVIEWER MUCUSDDYGGYLCHLTIMMYMPSNCHRALRKYSHYSICSTYTER NAIVEKEDPESPPYSALSTYTTYVALVEL NICERCHEECEFTYGHTNNINTHPPY NOBLEBLYISEISYMADOSERTHTCHVEL NUDERDGERSETTY NYLONMPH OAREDSIS OBESEOES OCCUREANTAL ODDERDLY OFTEN OGLESRES OKAYS OLDENDERIVE OMEGA ONIONSET OPERAIUMTIC ORBITDERGAN OTHERTER OUGHTNCE OVARY OWNER OXIDE OZONE PADDYGANGERINTLERNELNICNSYPALPERRCHRKARTYSTASTYTCHTIOTTYUSEYER PEACEACHARLCANEVENALNCENDSNISNNYONSONYRCHRKYSKYTALTERTTY PHASEONEONYOTO PIANOCKYECEETYLOTNCHOUSQUETCHTHYVOTXIEZZA PLACEAIDAINANEANKANTATEAZAEADEATUCKUMBUMEUMPUSH POACHINTISEKERKEYLARLIOLKAOPSPPYRCHUCHUNDWER PRANKAWNESSICEICKIDEIMEIMPINTIORISMIVYIZEONGOUDOVEOWLOXYUDEUNE PSALM PUCKSDGYFFYLSENCHPILPPYRERRGERSESHYSSYTTY QUACKAILAKEALMARKARTASHEENEERELLERYESTEUEICKIETILLILTIRKOTAOTE RABBIBIDCERDARDIOINYISELLYNCHPIDRERTIOTTYVELVENWERYONZOR REACHADYALMIGNLICMITPELVEL ROODSACHASTBINBOTCKYDEOGUEMANOMYOSTSISTORUGEUGHUNDUSEWDYYAL RHINOYME RIDERDGEFERFLEGHTGIDGORNSEPENPERSERSKYVALVERVET RUDDYDERGBYLERMMYMORNNYRALSTY SCALDALEALPALYANTAREARFARYENEENTOFFOLDOOPOOTOPEOREORNOUROUTOWLRAMRAPREWRUBUFF SEDANEDYIZEMENNSERUMRVEVENVERWER SHACKADEADYAFTAKEAKYALLAMEAPEAREARKARPAVEAWLEAFEAREENEEPEEREETELFELLIFTINEINYIREIRKIRTOALOCKOOTORTOUTOWYREDREWRUBRUGUCKUNTYER SIDLEEGEEVEGHTGMALLYLTSNCENUSRENSSYXTHXTYZER SKEATEINILLIMPIRTULKULLUNK SLACKAKEANGANTASHATEAVEEDSEEKEEPEETICEICKIDEIERIMEIMYINGINKOPEOSHOTHUMPUSHUTSYLY SMACKALLARTASHEARELLILEIRKITEOCKOKEOKYUTS SNACKAILAKEAREARLEAKEERIDEIFFIPEOOPOREORTOTSOUTOWYUFF SOAPYBERGGYLARLIDLVENICOTYRERRRYRTAUNDUTH SPACEADEANKAREARKASMATEAWNEAKEARECKEEDELLENDERMICEICYIKEILLINEIREITELATLITOILOOFOOKOOLOONOREORTOUTRAYREERIGURNURT SQUADUATUID STACKAFFAGEAIDAINAIRAKEALEALKALLAMPANDINKAREARKARTATEAVEEAKEALEAMEELEEPEERERNICKIFFILLINGINTOCKOKEOMPONEONYOOLOOPOREORKORMORYOUTOVEOWSRAPRAWRAYREWRIPRUMRUTUDYUFFUMPUNTYLE SUAVEGARLKYNNYNUPPERRGERLY SWAMPARMEAREATEEPEETELLIFTILLINEINGIPEIRLISHOONOOPORD SYRUP TABBYBLEBOOCITCKYINTKERLLYLONMERNGOPERRDYRRYSTESTYTTYUNTWNY TEACHAKSMPOMPTNETNORNTHPEEPID TOONSOTHASTDAYKENNALNICNNYPAZPICRCHRSOTALTEMUCHUGHWELWERXICXIN THANKEFTEIREMEEREESEETAICKIEFIGHINGINKIRDONGORNOSEREEROWROBUMBUMPYME TIARADALGERGHTLDEMERMIDNGENNYPSYTLE TRACEACKACTADEAILAINAITAMPASHAWLEADEATENDICKILLIPEITEOLLOOPOUTUCEUCKUERULYUMPUNKUSTUTH TULIPMMYMORNERNICTOR TWANGEAKEEDEETICEINEIRLIST UDDER ULCERTRA UNCLETIL UPENDPERSET URBANINE USAGEHERUALURP UTERITER VAGUELETLIDLORLUELVEPORSISULT VENOMNUERGERSERVE VICARDEOGILGORLERLLANYLOLAPERRALRUSSITSORSTATALVID VOCALDKAGUEICEMITTERUCHWEL WAFERGERGONISTIVEKENLTZNNASTETCHTERVER WEARYAVEDGEEDYIGHIRD WHACKALEARFEATEELEREICHIFFILEINEIRLISKITEOLEOOPOREOSE WIDENDERDOWDTHELDNCENCHNDYPERSERSPYTCHTTY WOMANODYRDYRLDRRYRSERSTRTH WRATHEAKECKENSESTINGISTITEONGYER YACHT YEARNASTSES YIELD YODELKELUNGUTH ZEBRA",
    dictStr: '{"AP":23,"AS":20,"DU":35,"GR":110,"IS":8,"LA":53,"NE":26,"SA":71,"AB":38,"AC":14,"AD":29,"AF":11,"AG":20,"AH":5,"AI":5,"AL":68,"AM":32,"AN":32,"AO":5,"AR":32,"AT":11,"AU":11,"AV":11,"AW":14,"AX":5,"AZ":5,"BA":71,"BE":56,"BO":50,"BI":17,"BL":92,"BR":101,"BU":56,"CA":83,"CE":11,"CH":122,"CI":20,"CL":92,"CO":50,"CR":107,"CU":23,"CY":8,"DA":29,"DE":35,"DO":44,"DI":41,"DR":65,"DW":8,"EA":20,"EB":8,"ED":8,"EE":5,"EG":5,"EI":5,"EJ":5,"EL":26,"EM":8,"EN":17,"EP":5,"EQ":8,"ER":14,"ES":5,"ET":11,"EV":17,"EX":29,"FA":44,"FE":38,"FI":62,"FL":95,"FO":50,"FR":56,"FU":26,"GA":38,"GO":35,"GE":17,"GH":8,"GI":17,"GL":47,"GN":14,"GU":41,"HA":56,"HE":32,"HI":11,"HO":47,"HU":29,"HY":5,"IC":5,"ID":8,"IG":5,"IM":11,"IN":38,"IR":8,"IT":5,"IV":8,"JA":8,"JE":14,"JI":8,"JO":11,"JU":23,"KA":5,"KH":5,"KI":17,"KN":23,"KO":5,"LE":62,"LI":50,"LL":5,"LO":53,"LU":26,"LY":14,"MA":83,"ME":44,"MI":29,"MO":83,"MU":44,"NA":29,"NI":26,"NO":29,"NU":14,"NY":8,"OA":8,"OB":8,"OC":11,"OD":8,"OF":5,"OG":8,"OK":5,"OL":11,"OM":5,"ON":8,"OP":11,"OR":11,"OT":8,"OU":8,"OV":5,"OW":5,"OX":5,"OZ":5,"PA":62,"PE":56,"PH":14,"PI":41,"PL":47,"PO":44,"PR":62,"PS":5,"PU":41,"QU":62,"RA":56,"RE":26,"RO":59,"RH":8,"RI":47,"RU":29,"SC":77,"SE":32,"SH":125,"SI":44,"SK":26,"SL":80,"SM":41,"SN":53,"SO":41,"SP":113,"SQ":11,"ST":170,"SU":26,"SW":53,"SY":5,"TA":59,"TE":29,"TO":62,"TH":68,"TI":35,"TR":86,"TU":20,"TW":26,"UD":5,"UL":8,"UN":8,"UP":11,"UR":8,"US":14,"UT":8,"VA":29,"VE":17,"VI":50,"VO":26,"WA":38,"WE":20,"WH":53,"WI":41,"WO":26,"WR":32,"YA":5,"YE":11,"YI":5,"YO":14,"ZE":5}',
    progress: 0,
    errStr: null,
    strLen: 0,
    interval: null,
  },
  onInit() {
    this.strLen = this.wordsStr.length;
    file.rmdir({
      uri: "internal://app/words",
      recursive: true,
      complete: () => {
        file.mkdir({
          uri: "internal://app/words",
          success: () => {
            this.progress = 0;
            this.interval = setInterval(this.continueWrite, 50);
          }
        });
      }
    });
  },
  continueWrite() {
    while (this.progress < this.strLen && this.wordsStr[this.progress] === ' ') this.progress++;
    if (this.progress >= this.strLen) {
      clearInterval(this.interval);
      file.writeText({
        uri: `internal://app/words/dict`,
        text: this.dictStr,
        fail: data => {
          clearInterval(this.interval);
          this.errStr = data;
        },
        success: () => {
          file.writeText({
            uri: `internal://app/words/status`,
            text: "1",
            fail: data => {
              clearInterval(this.interval);
              this.errStr = data;
            },
            success: () => {
              router.replace({uri: "/pages/main/main"});
            }
          });
        }
      });
      return;
    }

    const key = this.wordsStr[this.progress] + this.wordsStr[this.progress + 1];
    this.progress += 2;

    let vals = "";
    while (this.progress + 2 < this.strLen && this.wordsStr[this.progress] !== ' ') {
      const val = this.wordsStr[this.progress] + this.wordsStr[this.progress + 1] + this.wordsStr[this.progress + 2];
      this.progress += 3;
      vals += " " + val;
    }

    file.writeText({
      uri: `internal://app/words/${key}`,
      text: vals,
      fail: data => {
        clearInterval(this.interval);
        this.errStr = data;
      }
    });
  },
}